name: Update README with latest repos

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Git credentials
        run: |
          echo "${{ secrets.GIT_CREDENTIALS }}" > ~/.git-credentials
          git config --global credential.helper store
          git config --global user.name "ppossatto"
          git config --global user.email "${{ secrets.PPOSSATTO_EMAIL }}"
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Update README
        run: |
          curl -s https://api.github.com/users/ppossatto/repos > repos.json
          node .github/scripts/script.js
          
      - name: Commit and push changes
        run: |
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Cron job for updating README"
          git push